package model;

public enum SubmissionStatusEnum {
    PENDING,
    COMPILING,
    RUNNING_TESTS,
    WRONG_ANSWER,
    ACCEPTED,
    TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEEDED,
    RUNTIME_ERROR,
    COMPILATION_ERROR
}
